/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  daisyui: {
    themes: [
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
      "dim",
      "nord",
      "sunset",
      {
        oneSecond: {
          "primary": "#a3e33a",
          "secondary": "#000000",
          "accent": "#9caba2",
          "neutral": "#171926",
          "base-100": "#000000",
          "info": "#768ed6",
          "success": "#31c484",
          "warning": "#f4992a",
          "error": "#f77064",
        },
        coda: {
          "primary": "#0d51ff",
          "secondary": "#f3f4f6",
          "accent": "#000000",
          "neutral": "#171926",
          "base-100": "#ffffff",
          "info": "#768ed6",
          "success": "#31c484",
          "warning": "#f4992a",
          "error": "#f77064",
        },
      }
    ],
  },
  plugins: [require("daisyui")],
}
